# Generated by Django 4.2.23 on 2025-06-24 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='interview',
            name='additional_interviewers',
            field=models.ManyToManyField(blank=True, related_name='participated_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_application_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_application_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationfeedback',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationfeedback',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationfeedback',
            unique_together={('application', 'given_by', 'feedback_type')},
        ),
    ]
